name: Java CI with Maven

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        # Update package list
        sudo apt-get update
        
        # Remove any previous Chromium installation from Snap
        sudo snap remove chromium || true
        
        # Install Chromium from Ubuntu's official repositories
        sudo apt-get install -y chromium-browser

    - name: Download and install ChromeDriver
      run: |
        # Get the version of Chromium installed
        CHROME_VERSION=$(chromium-browser --version | awk '{print $3}' | cut -d '.' -f1,2)
        if [ -z "$CHROME_VERSION" ]; then
          echo "Error: Chromium version not found!"
          exit 1
        else
          echo "Chromium version found: $CHROME_VERSION"
        fi

        # Get the corresponding ChromeDriver version
        DRIVER_VERSION=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})

        if [ -z "$DRIVER_VERSION" ]; then
          echo "Error: Could not determine compatible ChromeDriver version!"
          exit 1
        fi

        # Download and install ChromeDriver
        wget https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build with Maven
      run: mvn clean verify
