name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip chromium-browser

    - name: Download and install ChromeDriver
      run: |
        # Try to get the current version of Chromium installed in the environment
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f1,2) || CHROME_VERSION=$(chromium-browser --version | awk '{print $3}' | cut -d '.' -f1,2)

        # If CHROME_VERSION is empty or not found, output an error
        if [ -z "$CHROME_VERSION" ]; then
          echo "Error: Chrome version not found!"
          exit 1
        fi

        # Download the corresponding ChromeDriver version based on the Chrome version
        DRIVER_VERSION=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})

        # Download ChromeDriver zip and extract it
        wget https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build with Maven
      run: mvn clean verify
