name: Java CI with Maven

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Get Chrome version
      run: |
        # Get the version of Chromium installed
        CHROME_VERSION=$(chromium-browser --version | awk '{print $3}' | cut -d '.' -f1,2)
        if [ -z "$CHROME_VERSION" ]; then
          echo "Error: Chromium version not found!"
          exit 1
        else
          echo "Chromium version found: $CHROME_VERSION"
        fi

    - name: Download and install ChromeDriver
      run: |
        # Get the correct ChromeDriver version manually for Chrome version 135
        DRIVER_VERSION="135.0.7049.114"
        DRIVER_URL="https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
        
        echo "Downloading ChromeDriver from: $DRIVER_URL"
        wget $DRIVER_URL
        if [ $? -ne 0 ]; then
          echo "Error: Failed to download ChromeDriver"
          exit 1
        fi
        
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build with Maven
      run: mvn clean verify
